<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.7 static/models/hands_model_lit.glb -s --transform -j --types
-->

<script lang="ts">
	import type * as THREE from 'three';

	import { type Snippet } from 'svelte';
	import { T, type Props } from '@threlte/core';
	import { useGltf, useDraco } from '@threlte/extras';
	import { asset } from '$app/paths';
	import { getScene } from '$lib/context';

	let {
		fallback,
		error,
		children,
		ref = $bindable(),
		...props
	}: Props<THREE.Group> & {
		ref?: THREE.Group;
		children?: Snippet<[{ ref: THREE.Group | undefined }]>;
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
	} = $props();

	type GLTFResult = {
		nodes: {
			LeftHand: THREE.Mesh;
			RightHand: THREE.Mesh;
		};
		materials: {
			hands: THREE.MeshStandardMaterial;
		};
	};

	const gltf = useGltf<GLTFResult>(asset('/models/hands_model_lit-transformed.glb'), {
		dracoLoader: useDraco()
	});

	const scene = getScene();
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Mesh
			castShadow
			receiveShadow
			geometry={gltf.nodes.LeftHand.geometry}
			material={gltf.materials.hands}
			position={[-scene.progress * 3, 0, 0]}
		/>
		<T.Mesh
			castShadow
			receiveShadow
			geometry={gltf.nodes.RightHand.geometry}
			material={gltf.materials.hands}
			position={[scene.progress * 3, 0, 0]}
		/>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
